default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: heavenly_pass
  pool: 5

development:
  <<: *default
  database: heavenly_development

test:
  <<: *default
  database: heavenly_test

production:
  <<: *default
  database: heavenly_production